version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: testapp_mysql
    environment:
      MYSQL_DATABASE: testapp
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: